LoggerModule: {
  file: logs/neon.log,
  level: debug,
  formatter: text, # text or json
  format: '2006-01-02 15:04:05',
  console: true,
  reportcaller: false,
}

Sfu: {
  listenAddr: ":7001",
  Cert: "",
  Key: "",
}

WebRTC: {
    singleport: 1936,
    portrange: [1937, 1938],
    candidates: {
      icelite: true,
      nat1to1: ['192.168.3.111'],
    },
    sdpsemantics: "unified-plan-with-fallback",
    mdns: true,
    timeouts: {
      disconnected: 5,
      failed: 20,
      keepalive: 2,
    },
    iceserver: {
      urls: ["stun:stun.l.google.com:19302"],
      username: "",
      credential: "",
    }
}

RtspModule: {
  server: {
    addr: "tcp://:3654",
    tcp: {
      Multicore: true,
      NemEventLoop: 10,
      TCPNoDelay: 0,
      LockOSThread: true,
      LogLevel: -1,
      ReusePort: true,
      ReuseAddr: true,
      SocketRecvBuffer: 1024,
    }
  }
}
